# print("\a")
# input("sound")
# print("text")
# input("press the enter")
# print("120-80=", 120 - 80)
# input("press the enter")
# print("120:67=", 120 // 67)
# input("press the enter")
# print("120%67=", 120 % 67)
# input("press the enter")
# input("\n\nPress the enter key to exit.")
# name = "word"
# print("i learn", name + "s")
# input("enter")
# v means variable
# v = input("Сколько будет два плюс два?")
# print("Ваш ответ: ", v)
# print("Верный ответ: ", 2+2)
# input("enter")
# q = "Полоков сумел устроиться на работу в городе; мусорщик, вывозит отходы."
# print("большие")
# print(q.upper())
# print("маленькие")
# print(q.lower())
# print("первые - большие")
# print(q.title())
# print("замена")
# print(q.replace("сумел", "смог"))
# print(q.replace("а", "@"))
# print(q.swapcase())
something = input("целое число ")
something = int(something)
etwas = float(input("дробное число "))
s = something + etwas
print("получится ", s)
input("enter")
