# print("\a")
# input("sound")
# print("text")
# input("press the enter")
# print("120-80=", 120 - 80)
# input("press the enter")
# print("120:67=", 120 // 67)
# input("press the enter")
# print("120%67=", 120 % 67)
# input("press the enter")
# input("\n\nPress the enter key to exit.")
name = "word"
print("i learn", name + "s")
input("enter")
